services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - NODE_ENV=test
            - DATABASE_HOST=localhost
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=scout_verse
        networks:
            - frontend
            - backend

    client:
        build:
            context: ./scoutverse
            dockerfile: Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./scoutverse:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3001:3000"
        networks:
            - frontend

    db:
        image: postgres:13
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=scout_verse
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - backend

volumes:
    postgres_data:

networks:
    frontend:
    backend:
